/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import demo.cosmos.core.policy.model.Link;
import demo.cosmos.core.policy.model.PolicyDetails;
import demo.cosmos.core.policy.model.ProposalBeneficiaryInfo;
import demo.cosmos.core.policy.model.ProposalCommunicationDetails;
import demo.cosmos.core.policy.model.ProposalQuestionInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * CreateProposal
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class CreateProposal   {
  @JsonProperty("affinityId")
  private Integer affinityId = null;

  @JsonProperty("beneficiaryList")
  private List<ProposalBeneficiaryInfo> beneficiaryList = null;

  @JsonProperty("branchId")
  private Integer branchId = null;

  @JsonProperty("communicationDetails")
  private ProposalCommunicationDetails communicationDetails = null;

  @JsonProperty("customerId")
  private Integer customerId = null;

  @JsonProperty("employeeCode")
  private String employeeCode = null;

  @JsonProperty("gstNo")
  private String gstNo = null;

  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("masterpolicyno")
  private String masterpolicyno = null;

  @JsonProperty("paymentOption")
  private String paymentOption = null;

  @JsonProperty("planId")
  private Integer planId = null;

  @JsonProperty("policyDetails")
  private PolicyDetails policyDetails = null;

  @JsonProperty("policyEndDate")
  private java.sql.Timestamp policyEndDate = null;

  @JsonProperty("policyId")
  private Integer policyId = null;

  @JsonProperty("policyStartDate")
  private java.sql.Timestamp policyStartDate = null;

  @JsonProperty("policyStatusId")
  private Integer policyStatusId = null;

  @JsonProperty("policyTerm")
  private String policyTerm = null;

  @JsonProperty("productId")
  private Integer productId = null;

  @JsonProperty("questionList")
  private List<ProposalQuestionInfo> questionList = null;

  @JsonProperty("sumInsured")
  private String sumInsured = null;

  public CreateProposal affinityId(Integer affinityId) {
    this.affinityId = affinityId;
    return this;
  }

  /**
   * Get affinityId
   * @return affinityId
   **/
  @JsonProperty("affinityId")
  @ApiModelProperty(value = "")
  public Integer getAffinityId() {
    return affinityId;
  }

  public void setAffinityId(Integer affinityId) {
    this.affinityId = affinityId;
  }

  public CreateProposal beneficiaryList(List<ProposalBeneficiaryInfo> beneficiaryList) {
    this.beneficiaryList = beneficiaryList;
    return this;
  }

  public CreateProposal addBeneficiaryListItem(ProposalBeneficiaryInfo beneficiaryListItem) {
    if (this.beneficiaryList == null) {
      this.beneficiaryList = new ArrayList<ProposalBeneficiaryInfo>();
    }
    this.beneficiaryList.add(beneficiaryListItem);
    return this;
  }

  /**
   * Get beneficiaryList
   * @return beneficiaryList
   **/
  @JsonProperty("beneficiaryList")
  @ApiModelProperty(value = "")
  public List<ProposalBeneficiaryInfo> getBeneficiaryList() {
    return beneficiaryList;
  }

  public void setBeneficiaryList(List<ProposalBeneficiaryInfo> beneficiaryList) {
    this.beneficiaryList = beneficiaryList;
  }

  public CreateProposal branchId(Integer branchId) {
    this.branchId = branchId;
    return this;
  }

  /**
   * Get branchId
   * @return branchId
   **/
  @JsonProperty("branchId")
  @ApiModelProperty(value = "")
  public Integer getBranchId() {
    return branchId;
  }

  public void setBranchId(Integer branchId) {
    this.branchId = branchId;
  }

  public CreateProposal communicationDetails(ProposalCommunicationDetails communicationDetails) {
    this.communicationDetails = communicationDetails;
    return this;
  }

  /**
   * Get communicationDetails
   * @return communicationDetails
   **/
  @JsonProperty("communicationDetails")
  @ApiModelProperty(value = "")
  public ProposalCommunicationDetails getCommunicationDetails() {
    return communicationDetails;
  }

  public void setCommunicationDetails(ProposalCommunicationDetails communicationDetails) {
    this.communicationDetails = communicationDetails;
  }

  public CreateProposal customerId(Integer customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Get customerId
   * @return customerId
   **/
  @JsonProperty("customerId")
  @ApiModelProperty(value = "")
  public Integer getCustomerId() {
    return customerId;
  }

  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }

  public CreateProposal employeeCode(String employeeCode) {
    this.employeeCode = employeeCode;
    return this;
  }

  /**
   * Get employeeCode
   * @return employeeCode
   **/
  @JsonProperty("employeeCode")
  @ApiModelProperty(value = "")
  public String getEmployeeCode() {
    return employeeCode;
  }

  public void setEmployeeCode(String employeeCode) {
    this.employeeCode = employeeCode;
  }

  public CreateProposal gstNo(String gstNo) {
    this.gstNo = gstNo;
    return this;
  }

  /**
   * Get gstNo
   * @return gstNo
   **/
  @JsonProperty("gstNo")
  @ApiModelProperty(value = "")
  public String getGstNo() {
    return gstNo;
  }

  public void setGstNo(String gstNo) {
    this.gstNo = gstNo;
  }

  public CreateProposal links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CreateProposal addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   **/
  @JsonProperty("links")
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public CreateProposal masterpolicyno(String masterpolicyno) {
    this.masterpolicyno = masterpolicyno;
    return this;
  }

  /**
   * Get masterpolicyno
   * @return masterpolicyno
   **/
  @JsonProperty("masterpolicyno")
  @ApiModelProperty(value = "")
  public String getMasterpolicyno() {
    return masterpolicyno;
  }

  public void setMasterpolicyno(String masterpolicyno) {
    this.masterpolicyno = masterpolicyno;
  }

  public CreateProposal paymentOption(String paymentOption) {
    this.paymentOption = paymentOption;
    return this;
  }

  /**
   * Get paymentOption
   * @return paymentOption
   **/
  @JsonProperty("paymentOption")
  @ApiModelProperty(value = "")
  public String getPaymentOption() {
    return paymentOption;
  }

  public void setPaymentOption(String paymentOption) {
    this.paymentOption = paymentOption;
  }

  public CreateProposal planId(Integer planId) {
    this.planId = planId;
    return this;
  }

  /**
   * Get planId
   * @return planId
   **/
  @JsonProperty("planId")
  @ApiModelProperty(value = "")
  public Integer getPlanId() {
    return planId;
  }

  public void setPlanId(Integer planId) {
    this.planId = planId;
  }

  public CreateProposal policyDetails(PolicyDetails policyDetails) {
    this.policyDetails = policyDetails;
    return this;
  }

  /**
   * Get policyDetails
   * @return policyDetails
   **/
  @JsonProperty("policyDetails")
  @ApiModelProperty(value = "")
  public PolicyDetails getPolicyDetails() {
    return policyDetails;
  }

  public void setPolicyDetails(PolicyDetails policyDetails) {
    this.policyDetails = policyDetails;
  }

  public CreateProposal policyEndDate(java.sql.Timestamp policyEndDate) {
    this.policyEndDate = policyEndDate;
    return this;
  }

  /**
   * Get policyEndDate
   * @return policyEndDate
   **/
  @JsonProperty("policyEndDate")
  @ApiModelProperty(value = "")
  public java.sql.Timestamp getPolicyEndDate() {
    return policyEndDate;
  }

  public void setPolicyEndDate(java.sql.Timestamp policyEndDate) {
    this.policyEndDate = policyEndDate;
  }

  public CreateProposal policyId(Integer policyId) {
    this.policyId = policyId;
    return this;
  }

  /**
   * Get policyId
   * @return policyId
   **/
  @JsonProperty("policyId")
  @ApiModelProperty(value = "")
  public Integer getPolicyId() {
    return policyId;
  }

  public void setPolicyId(Integer policyId) {
    this.policyId = policyId;
  }

  public CreateProposal policyStartDate(java.sql.Timestamp policyStartDate) {
    this.policyStartDate = policyStartDate;
    return this;
  }

  /**
   * Get policyStartDate
   * @return policyStartDate
   **/
  @JsonProperty("policyStartDate")
  @ApiModelProperty(value = "")
  public java.sql.Timestamp getPolicyStartDate() {
    return policyStartDate;
  }

  public void setPolicyStartDate(java.sql.Timestamp policyStartDate) {
    this.policyStartDate = policyStartDate;
  }

  public CreateProposal policyStatusId(Integer policyStatusId) {
    this.policyStatusId = policyStatusId;
    return this;
  }

  /**
   * Get policyStatusId
   * @return policyStatusId
   **/
  @JsonProperty("policyStatusId")
  @ApiModelProperty(value = "")
  public Integer getPolicyStatusId() {
    return policyStatusId;
  }

  public void setPolicyStatusId(Integer policyStatusId) {
    this.policyStatusId = policyStatusId;
  }

  public CreateProposal policyTerm(String policyTerm) {
    this.policyTerm = policyTerm;
    return this;
  }

  /**
   * Get policyTerm
   * @return policyTerm
   **/
  @JsonProperty("policyTerm")
  @ApiModelProperty(value = "")
  public String getPolicyTerm() {
    return policyTerm;
  }

  public void setPolicyTerm(String policyTerm) {
    this.policyTerm = policyTerm;
  }

  public CreateProposal productId(Integer productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   **/
  @JsonProperty("productId")
  @ApiModelProperty(value = "")
  public Integer getProductId() {
    return productId;
  }

  public void setProductId(Integer productId) {
    this.productId = productId;
  }

  public CreateProposal questionList(List<ProposalQuestionInfo> questionList) {
    this.questionList = questionList;
    return this;
  }

  public CreateProposal addQuestionListItem(ProposalQuestionInfo questionListItem) {
    if (this.questionList == null) {
      this.questionList = new ArrayList<ProposalQuestionInfo>();
    }
    this.questionList.add(questionListItem);
    return this;
  }

  /**
   * Get questionList
   * @return questionList
   **/
  @JsonProperty("questionList")
  @ApiModelProperty(value = "")
  public List<ProposalQuestionInfo> getQuestionList() {
    return questionList;
  }

  public void setQuestionList(List<ProposalQuestionInfo> questionList) {
    this.questionList = questionList;
  }

  public CreateProposal sumInsured(String sumInsured) {
    this.sumInsured = sumInsured;
    return this;
  }

  /**
   * Get sumInsured
   * @return sumInsured
   **/
  @JsonProperty("sumInsured")
  @ApiModelProperty(value = "")
  public String getSumInsured() {
    return sumInsured;
  }

  public void setSumInsured(String sumInsured) {
    this.sumInsured = sumInsured;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateProposal createProposal = (CreateProposal) o;
    return Objects.equals(this.affinityId, createProposal.affinityId) &&
        Objects.equals(this.beneficiaryList, createProposal.beneficiaryList) &&
        Objects.equals(this.branchId, createProposal.branchId) &&
        Objects.equals(this.communicationDetails, createProposal.communicationDetails) &&
        Objects.equals(this.customerId, createProposal.customerId) &&
        Objects.equals(this.employeeCode, createProposal.employeeCode) &&
        Objects.equals(this.gstNo, createProposal.gstNo) &&
        Objects.equals(this.links, createProposal.links) &&
        Objects.equals(this.masterpolicyno, createProposal.masterpolicyno) &&
        Objects.equals(this.paymentOption, createProposal.paymentOption) &&
        Objects.equals(this.planId, createProposal.planId) &&
        Objects.equals(this.policyDetails, createProposal.policyDetails) &&
        Objects.equals(this.policyEndDate, createProposal.policyEndDate) &&
        Objects.equals(this.policyId, createProposal.policyId) &&
        Objects.equals(this.policyStartDate, createProposal.policyStartDate) &&
        Objects.equals(this.policyStatusId, createProposal.policyStatusId) &&
        Objects.equals(this.policyTerm, createProposal.policyTerm) &&
        Objects.equals(this.productId, createProposal.productId) &&
        Objects.equals(this.questionList, createProposal.questionList) &&
        Objects.equals(this.sumInsured, createProposal.sumInsured);
  }

  @Override
  public int hashCode() {
    return Objects.hash(affinityId, beneficiaryList, branchId, communicationDetails, customerId, employeeCode, gstNo, links, masterpolicyno, paymentOption, planId, policyDetails, policyEndDate, policyId, policyStartDate, policyStatusId, policyTerm, productId, questionList, sumInsured);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateProposal {\n");
    
    sb.append("    affinityId: ").append(toIndentedString(affinityId)).append("\n");
    sb.append("    beneficiaryList: ").append(toIndentedString(beneficiaryList)).append("\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    communicationDetails: ").append(toIndentedString(communicationDetails)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    employeeCode: ").append(toIndentedString(employeeCode)).append("\n");
    sb.append("    gstNo: ").append(toIndentedString(gstNo)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    masterpolicyno: ").append(toIndentedString(masterpolicyno)).append("\n");
    sb.append("    paymentOption: ").append(toIndentedString(paymentOption)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    policyDetails: ").append(toIndentedString(policyDetails)).append("\n");
    sb.append("    policyEndDate: ").append(toIndentedString(policyEndDate)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    policyStartDate: ").append(toIndentedString(policyStartDate)).append("\n");
    sb.append("    policyStatusId: ").append(toIndentedString(policyStatusId)).append("\n");
    sb.append("    policyTerm: ").append(toIndentedString(policyTerm)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    questionList: ").append(toIndentedString(questionList)).append("\n");
    sb.append("    sumInsured: ").append(toIndentedString(sumInsured)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

