/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.validation.constraints.*;

/**
 * PlanDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class PlanDetails   {
  @JsonProperty("ageRange")
  private Integer ageRange = null;

  @JsonProperty("grosspremium")
  private BigDecimal grosspremium = null;

  @JsonProperty("premium")
  private BigDecimal premium = null;

  @JsonProperty("sumInsured")
  private Integer sumInsured = null;

  public PlanDetails ageRange(Integer ageRange) {
    this.ageRange = ageRange;
    return this;
  }

  /**
   * Get ageRange
   * @return ageRange
   **/
  @JsonProperty("ageRange")
  @ApiModelProperty(value = "")
  public Integer getAgeRange() {
    return ageRange;
  }

  public void setAgeRange(Integer ageRange) {
    this.ageRange = ageRange;
  }

  public PlanDetails grosspremium(BigDecimal grosspremium) {
    this.grosspremium = grosspremium;
    return this;
  }

  /**
   * Get grosspremium
   * @return grosspremium
   **/
  @JsonProperty("grosspremium")
  @ApiModelProperty(value = "")
  public BigDecimal getGrosspremium() {
    return grosspremium;
  }

  public void setGrosspremium(BigDecimal grosspremium) {
    this.grosspremium = grosspremium;
  }

  public PlanDetails premium(BigDecimal premium) {
    this.premium = premium;
    return this;
  }

  /**
   * Get premium
   * @return premium
   **/
  @JsonProperty("premium")
  @ApiModelProperty(value = "")
  public BigDecimal getPremium() {
    return premium;
  }

  public void setPremium(BigDecimal premium) {
    this.premium = premium;
  }

  public PlanDetails sumInsured(Integer sumInsured) {
    this.sumInsured = sumInsured;
    return this;
  }

  /**
   * Get sumInsured
   * @return sumInsured
   **/
  @JsonProperty("sumInsured")
  @ApiModelProperty(value = "")
  public Integer getSumInsured() {
    return sumInsured;
  }

  public void setSumInsured(Integer sumInsured) {
    this.sumInsured = sumInsured;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanDetails planDetails = (PlanDetails) o;
    return Objects.equals(this.ageRange, planDetails.ageRange) &&
        Objects.equals(this.grosspremium, planDetails.grosspremium) &&
        Objects.equals(this.premium, planDetails.premium) &&
        Objects.equals(this.sumInsured, planDetails.sumInsured);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ageRange, grosspremium, premium, sumInsured);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanDetails {\n");
    
    sb.append("    ageRange: ").append(toIndentedString(ageRange)).append("\n");
    sb.append("    grosspremium: ").append(toIndentedString(grosspremium)).append("\n");
    sb.append("    premium: ").append(toIndentedString(premium)).append("\n");
    sb.append("    sumInsured: ").append(toIndentedString(sumInsured)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

