/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import demo.cosmos.core.policy.model.Link;
import demo.cosmos.core.policy.model.PlanDetails;
import demo.cosmos.core.policy.model.PlanSumInsuredDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * PlansResource
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class PlansResource   {
  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("planDetails")
  private List<PlanDetails> planDetails = null;

  @JsonProperty("planid")
  private Integer planid = null;

  @JsonProperty("policytype")
  private String policytype = null;

  @JsonProperty("productid")
  private Integer productid = null;

  @JsonProperty("sumInsuredinLakhs")
  private List<PlanSumInsuredDetails> sumInsuredinLakhs = null;

  public PlansResource links(List<Link> links) {
    this.links = links;
    return this;
  }

  public PlansResource addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   **/
  @JsonProperty("links")
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public PlansResource planDetails(List<PlanDetails> planDetails) {
    this.planDetails = planDetails;
    return this;
  }

  public PlansResource addPlanDetailsItem(PlanDetails planDetailsItem) {
    if (this.planDetails == null) {
      this.planDetails = new ArrayList<PlanDetails>();
    }
    this.planDetails.add(planDetailsItem);
    return this;
  }

  /**
   * Get planDetails
   * @return planDetails
   **/
  @JsonProperty("planDetails")
  @ApiModelProperty(value = "")
  public List<PlanDetails> getPlanDetails() {
    return planDetails;
  }

  public void setPlanDetails(List<PlanDetails> planDetails) {
    this.planDetails = planDetails;
  }

  public PlansResource planid(Integer planid) {
    this.planid = planid;
    return this;
  }

  /**
   * Get planid
   * @return planid
   **/
  @JsonProperty("planid")
  @ApiModelProperty(value = "")
  public Integer getPlanid() {
    return planid;
  }

  public void setPlanid(Integer planid) {
    this.planid = planid;
  }

  public PlansResource policytype(String policytype) {
    this.policytype = policytype;
    return this;
  }

  /**
   * Get policytype
   * @return policytype
   **/
  @JsonProperty("policytype")
  @ApiModelProperty(value = "")
  public String getPolicytype() {
    return policytype;
  }

  public void setPolicytype(String policytype) {
    this.policytype = policytype;
  }

  public PlansResource productid(Integer productid) {
    this.productid = productid;
    return this;
  }

  /**
   * Get productid
   * @return productid
   **/
  @JsonProperty("productid")
  @ApiModelProperty(value = "")
  public Integer getProductid() {
    return productid;
  }

  public void setProductid(Integer productid) {
    this.productid = productid;
  }

  public PlansResource sumInsuredinLakhs(List<PlanSumInsuredDetails> sumInsuredinLakhs) {
    this.sumInsuredinLakhs = sumInsuredinLakhs;
    return this;
  }

  public PlansResource addSumInsuredinLakhsItem(PlanSumInsuredDetails sumInsuredinLakhsItem) {
    if (this.sumInsuredinLakhs == null) {
      this.sumInsuredinLakhs = new ArrayList<PlanSumInsuredDetails>();
    }
    this.sumInsuredinLakhs.add(sumInsuredinLakhsItem);
    return this;
  }

  /**
   * Get sumInsuredinLakhs
   * @return sumInsuredinLakhs
   **/
  @JsonProperty("sumInsuredinLakhs")
  @ApiModelProperty(value = "")
  public List<PlanSumInsuredDetails> getSumInsuredinLakhs() {
    return sumInsuredinLakhs;
  }

  public void setSumInsuredinLakhs(List<PlanSumInsuredDetails> sumInsuredinLakhs) {
    this.sumInsuredinLakhs = sumInsuredinLakhs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlansResource plansResource = (PlansResource) o;
    return Objects.equals(this.links, plansResource.links) &&
        Objects.equals(this.planDetails, plansResource.planDetails) &&
        Objects.equals(this.planid, plansResource.planid) &&
        Objects.equals(this.policytype, plansResource.policytype) &&
        Objects.equals(this.productid, plansResource.productid) &&
        Objects.equals(this.sumInsuredinLakhs, plansResource.sumInsuredinLakhs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, planDetails, planid, policytype, productid, sumInsuredinLakhs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlansResource {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    planDetails: ").append(toIndentedString(planDetails)).append("\n");
    sb.append("    planid: ").append(toIndentedString(planid)).append("\n");
    sb.append("    policytype: ").append(toIndentedString(policytype)).append("\n");
    sb.append("    productid: ").append(toIndentedString(productid)).append("\n");
    sb.append("    sumInsuredinLakhs: ").append(toIndentedString(sumInsuredinLakhs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

