/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * PlanSumInsuredDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class PlanSumInsuredDetails   {
  @JsonProperty("sumInsured")
  private Integer sumInsured = null;

  public PlanSumInsuredDetails sumInsured(Integer sumInsured) {
    this.sumInsured = sumInsured;
    return this;
  }

  /**
   * Get sumInsured
   * @return sumInsured
   **/
  @JsonProperty("sumInsured")
  @ApiModelProperty(value = "")
  public Integer getSumInsured() {
    return sumInsured;
  }

  public void setSumInsured(Integer sumInsured) {
    this.sumInsured = sumInsured;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanSumInsuredDetails planSumInsuredDetails = (PlanSumInsuredDetails) o;
    return Objects.equals(this.sumInsured, planSumInsuredDetails.sumInsured);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sumInsured);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanSumInsuredDetails {\n");
    
    sb.append("    sumInsured: ").append(toIndentedString(sumInsured)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

