/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import javax.validation.constraints.*;

/**
 * PolicyDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class PolicyDetails   {
  @JsonProperty("affinityid")
  private Integer affinityid = null;

  @JsonProperty("branchId")
  private Integer branchId = null;

  @JsonProperty("covernoteno")
  private Integer covernoteno = null;

  @JsonProperty("customerid")
  private Integer customerid = null;

  @JsonProperty("employeecode")
  private String employeecode = null;

  @JsonProperty("lastUpdatedBy")
  private Integer lastUpdatedBy = null;

  @JsonProperty("lastUpdatedDate")
  private Date lastUpdatedDate = null;

  @JsonProperty("masterpolicyno")
  private Integer masterpolicyno = null;

  @JsonProperty("planId")
  private Integer planId = null;

  @JsonProperty("policyEndDate")
  private java.sql.Timestamp policyEndDate = null;

  @JsonProperty("policyId")
  private Integer policyId = null;

  @JsonProperty("policyStartDate")
  private java.sql.Timestamp policyStartDate = null;

  @JsonProperty("policyStatusId")
  private Integer policyStatusId = null;

  @JsonProperty("policyterm")
  private Integer policyterm = null;

  @JsonProperty("productID")
  private Integer productID = null;

  public PolicyDetails affinityid(Integer affinityid) {
    this.affinityid = affinityid;
    return this;
  }

  /**
   * Get affinityid
   * @return affinityid
   **/
  @JsonProperty("affinityid")
  @ApiModelProperty(value = "")
  public Integer getAffinityid() {
    return affinityid;
  }

  public void setAffinityid(Integer affinityid) {
    this.affinityid = affinityid;
  }

  public PolicyDetails branchId(Integer branchId) {
    this.branchId = branchId;
    return this;
  }

  /**
   * Get branchId
   * @return branchId
   **/
  @JsonProperty("branchId")
  @ApiModelProperty(value = "")
  public Integer getBranchId() {
    return branchId;
  }

  public void setBranchId(Integer branchId) {
    this.branchId = branchId;
  }

  public PolicyDetails covernoteno(Integer covernoteno) {
    this.covernoteno = covernoteno;
    return this;
  }

  /**
   * Get covernoteno
   * @return covernoteno
   **/
  @JsonProperty("covernoteno")
  @ApiModelProperty(value = "")
  public Integer getCovernoteno() {
    return covernoteno;
  }

  public void setCovernoteno(Integer covernoteno) {
    this.covernoteno = covernoteno;
  }

  public PolicyDetails customerid(Integer customerid) {
    this.customerid = customerid;
    return this;
  }

  /**
   * Get customerid
   * @return customerid
   **/
  @JsonProperty("customerid")
  @ApiModelProperty(value = "")
  public Integer getCustomerid() {
    return customerid;
  }

  public void setCustomerid(Integer customerid) {
    this.customerid = customerid;
  }

  public PolicyDetails employeecode(String employeecode) {
    this.employeecode = employeecode;
    return this;
  }

  /**
   * Get employeecode
   * @return employeecode
   **/
  @JsonProperty("employeecode")
  @ApiModelProperty(value = "")
  public String getEmployeecode() {
    return employeecode;
  }

  public void setEmployeecode(String employeecode) {
    this.employeecode = employeecode;
  }

  public PolicyDetails lastUpdatedBy(Integer lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

  /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
   **/
  @JsonProperty("lastUpdatedBy")
  @ApiModelProperty(value = "")
  public Integer getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(Integer lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public PolicyDetails lastUpdatedDate(Date lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
    return this;
  }

  /**
   * Get lastUpdatedDate
   * @return lastUpdatedDate
   **/
  @JsonProperty("lastUpdatedDate")
  @ApiModelProperty(value = "")
  public Date getLastUpdatedDate() {
    return lastUpdatedDate;
  }

  public void setLastUpdatedDate(Date lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
  }

  public PolicyDetails masterpolicyno(Integer masterpolicyno) {
    this.masterpolicyno = masterpolicyno;
    return this;
  }

  /**
   * Get masterpolicyno
   * @return masterpolicyno
   **/
  @JsonProperty("masterpolicyno")
  @ApiModelProperty(value = "")
  public Integer getMasterpolicyno() {
    return masterpolicyno;
  }

  public void setMasterpolicyno(Integer masterpolicyno) {
    this.masterpolicyno = masterpolicyno;
  }

  public PolicyDetails planId(Integer planId) {
    this.planId = planId;
    return this;
  }

  /**
   * Get planId
   * @return planId
   **/
  @JsonProperty("planId")
  @ApiModelProperty(value = "")
  public Integer getPlanId() {
    return planId;
  }

  public void setPlanId(Integer planId) {
    this.planId = planId;
  }

  public PolicyDetails policyEndDate(java.sql.Timestamp policyEndDate) {
    this.policyEndDate = policyEndDate;
    return this;
  }

  /**
   * Get policyEndDate
   * @return policyEndDate
   **/
  @JsonProperty("policyEndDate")
  @ApiModelProperty(value = "")
  public java.sql.Timestamp getPolicyEndDate() {
    return policyEndDate;
  }

  public void setPolicyEndDate(java.sql.Timestamp policyEndDate) {
    this.policyEndDate = policyEndDate;
  }

  public PolicyDetails policyId(Integer policyId) {
    this.policyId = policyId;
    return this;
  }

  /**
   * Get policyId
   * @return policyId
   **/
  @JsonProperty("policyId")
  @ApiModelProperty(value = "")
  public Integer getPolicyId() {
    return policyId;
  }

  public void setPolicyId(Integer policyId) {
    this.policyId = policyId;
  }

  public PolicyDetails policyStartDate(java.sql.Timestamp policyStartDate) {
    this.policyStartDate = policyStartDate;
    return this;
  }

  /**
   * Get policyStartDate
   * @return policyStartDate
   **/
  @JsonProperty("policyStartDate")
  @ApiModelProperty(value = "")
  public java.sql.Timestamp getPolicyStartDate() {
    return policyStartDate;
  }

  public void setPolicyStartDate(java.sql.Timestamp policyStartDate) {
    this.policyStartDate = policyStartDate;
  }

  public PolicyDetails policyStatusId(Integer policyStatusId) {
    this.policyStatusId = policyStatusId;
    return this;
  }

  /**
   * Get policyStatusId
   * @return policyStatusId
   **/
  @JsonProperty("policyStatusId")
  @ApiModelProperty(value = "")
  public Integer getPolicyStatusId() {
    return policyStatusId;
  }

  public void setPolicyStatusId(Integer policyStatusId) {
    this.policyStatusId = policyStatusId;
  }

  public PolicyDetails policyterm(Integer policyterm) {
    this.policyterm = policyterm;
    return this;
  }

  /**
   * Get policyterm
   * @return policyterm
   **/
  @JsonProperty("policyterm")
  @ApiModelProperty(value = "")
  public Integer getPolicyterm() {
    return policyterm;
  }

  public void setPolicyterm(Integer policyterm) {
    this.policyterm = policyterm;
  }

  public PolicyDetails productID(Integer productID) {
    this.productID = productID;
    return this;
  }

  /**
   * Get productID
   * @return productID
   **/
  @JsonProperty("productID")
  @ApiModelProperty(value = "")
  public Integer getProductID() {
    return productID;
  }

  public void setProductID(Integer productID) {
    this.productID = productID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyDetails policyDetails = (PolicyDetails) o;
    return Objects.equals(this.affinityid, policyDetails.affinityid) &&
        Objects.equals(this.branchId, policyDetails.branchId) &&
        Objects.equals(this.covernoteno, policyDetails.covernoteno) &&
        Objects.equals(this.customerid, policyDetails.customerid) &&
        Objects.equals(this.employeecode, policyDetails.employeecode) &&
        Objects.equals(this.lastUpdatedBy, policyDetails.lastUpdatedBy) &&
        Objects.equals(this.lastUpdatedDate, policyDetails.lastUpdatedDate) &&
        Objects.equals(this.masterpolicyno, policyDetails.masterpolicyno) &&
        Objects.equals(this.planId, policyDetails.planId) &&
        Objects.equals(this.policyEndDate, policyDetails.policyEndDate) &&
        Objects.equals(this.policyId, policyDetails.policyId) &&
        Objects.equals(this.policyStartDate, policyDetails.policyStartDate) &&
        Objects.equals(this.policyStatusId, policyDetails.policyStatusId) &&
        Objects.equals(this.policyterm, policyDetails.policyterm) &&
        Objects.equals(this.productID, policyDetails.productID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(affinityid, branchId, covernoteno, customerid, employeecode, lastUpdatedBy, lastUpdatedDate, masterpolicyno, planId, policyEndDate, policyId, policyStartDate, policyStatusId, policyterm, productID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyDetails {\n");
    
    sb.append("    affinityid: ").append(toIndentedString(affinityid)).append("\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    covernoteno: ").append(toIndentedString(covernoteno)).append("\n");
    sb.append("    customerid: ").append(toIndentedString(customerid)).append("\n");
    sb.append("    employeecode: ").append(toIndentedString(employeecode)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    lastUpdatedDate: ").append(toIndentedString(lastUpdatedDate)).append("\n");
    sb.append("    masterpolicyno: ").append(toIndentedString(masterpolicyno)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    policyEndDate: ").append(toIndentedString(policyEndDate)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    policyStartDate: ").append(toIndentedString(policyStartDate)).append("\n");
    sb.append("    policyStatusId: ").append(toIndentedString(policyStatusId)).append("\n");
    sb.append("    policyterm: ").append(toIndentedString(policyterm)).append("\n");
    sb.append("    productID: ").append(toIndentedString(productID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

