/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import demo.cosmos.core.policy.model.CreateProposal;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * PolicyCreationRequestWrapper
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class PolicyCreationRequestWrapper   {
  @JsonProperty("policyDetails")
  private CreateProposal policyDetails = null;

  public PolicyCreationRequestWrapper policyDetails(CreateProposal policyDetails) {
    this.policyDetails = policyDetails;
    return this;
  }

  /**
   * Get policyDetails
   * @return policyDetails
   **/
  @JsonProperty("policyDetails")
  @ApiModelProperty(value = "")
  public CreateProposal getPolicyDetails() {
    return policyDetails;
  }

  public void setPolicyDetails(CreateProposal policyDetails) {
    this.policyDetails = policyDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyCreationRequestWrapper policyCreationRequestWrapper = (PolicyCreationRequestWrapper) o;
    return Objects.equals(this.policyDetails, policyCreationRequestWrapper.policyDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(policyDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyCreationRequestWrapper {\n");
    
    sb.append("    policyDetails: ").append(toIndentedString(policyDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

