/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import demo.cosmos.core.policy.model.Link;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.validation.constraints.*;

/**
 * ProductResource
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class ProductResource   {
  @JsonProperty("backdatedinception")
  private Boolean backdatedinception = null;

  @JsonProperty("backdatedinceptionrange")
  private Integer backdatedinceptionrange = null;

  @JsonProperty("effectivedate")
  private Date effectivedate = null;

  @JsonProperty("enddate")
  private Date enddate = null;

  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("lobid")
  private Integer lobid = null;

  @JsonProperty("productid")
  private Integer productid = null;

  @JsonProperty("productname")
  private String productname = null;

  @JsonProperty("riskstartdaterange")
  private Integer riskstartdaterange = null;

  @JsonProperty("shortProductname")
  private String shortProductname = null;

  @JsonProperty("startdate")
  private Date startdate = null;

  public ProductResource backdatedinception(Boolean backdatedinception) {
    this.backdatedinception = backdatedinception;
    return this;
  }

  /**
   * Get backdatedinception
   * @return backdatedinception
   **/
  @JsonProperty("backdatedinception")
  @ApiModelProperty(value = "")
  public Boolean isBackdatedinception() {
    return backdatedinception;
  }

  public void setBackdatedinception(Boolean backdatedinception) {
    this.backdatedinception = backdatedinception;
  }

  public ProductResource backdatedinceptionrange(Integer backdatedinceptionrange) {
    this.backdatedinceptionrange = backdatedinceptionrange;
    return this;
  }

  /**
   * Get backdatedinceptionrange
   * @return backdatedinceptionrange
   **/
  @JsonProperty("backdatedinceptionrange")
  @ApiModelProperty(value = "")
  public Integer getBackdatedinceptionrange() {
    return backdatedinceptionrange;
  }

  public void setBackdatedinceptionrange(Integer backdatedinceptionrange) {
    this.backdatedinceptionrange = backdatedinceptionrange;
  }

  public ProductResource effectivedate(Date effectivedate) {
    this.effectivedate = effectivedate;
    return this;
  }

  /**
   * Get effectivedate
   * @return effectivedate
   **/
  @JsonProperty("effectivedate")
  @ApiModelProperty(value = "")
  public Date getEffectivedate() {
    return effectivedate;
  }

  public void setEffectivedate(Date effectivedate) {
    this.effectivedate = effectivedate;
  }

  public ProductResource enddate(Date enddate) {
    this.enddate = enddate;
    return this;
  }

  /**
   * Get enddate
   * @return enddate
   **/
  @JsonProperty("enddate")
  @ApiModelProperty(value = "")
  public Date getEnddate() {
    return enddate;
  }

  public void setEnddate(Date enddate) {
    this.enddate = enddate;
  }

  public ProductResource links(List<Link> links) {
    this.links = links;
    return this;
  }

  public ProductResource addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   **/
  @JsonProperty("links")
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public ProductResource lobid(Integer lobid) {
    this.lobid = lobid;
    return this;
  }

  /**
   * Get lobid
   * @return lobid
   **/
  @JsonProperty("lobid")
  @ApiModelProperty(value = "")
  public Integer getLobid() {
    return lobid;
  }

  public void setLobid(Integer lobid) {
    this.lobid = lobid;
  }

  public ProductResource productid(Integer productid) {
    this.productid = productid;
    return this;
  }

  /**
   * Get productid
   * @return productid
   **/
  @JsonProperty("productid")
  @ApiModelProperty(value = "")
  public Integer getProductid() {
    return productid;
  }

  public void setProductid(Integer productid) {
    this.productid = productid;
  }

  public ProductResource productname(String productname) {
    this.productname = productname;
    return this;
  }

  /**
   * Get productname
   * @return productname
   **/
  @JsonProperty("productname")
  @ApiModelProperty(value = "")
  public String getProductname() {
    return productname;
  }

  public void setProductname(String productname) {
    this.productname = productname;
  }

  public ProductResource riskstartdaterange(Integer riskstartdaterange) {
    this.riskstartdaterange = riskstartdaterange;
    return this;
  }

  /**
   * Get riskstartdaterange
   * @return riskstartdaterange
   **/
  @JsonProperty("riskstartdaterange")
  @ApiModelProperty(value = "")
  public Integer getRiskstartdaterange() {
    return riskstartdaterange;
  }

  public void setRiskstartdaterange(Integer riskstartdaterange) {
    this.riskstartdaterange = riskstartdaterange;
  }

  public ProductResource shortProductname(String shortProductname) {
    this.shortProductname = shortProductname;
    return this;
  }

  /**
   * Get shortProductname
   * @return shortProductname
   **/
  @JsonProperty("shortProductname")
  @ApiModelProperty(value = "")
  public String getShortProductname() {
    return shortProductname;
  }

  public void setShortProductname(String shortProductname) {
    this.shortProductname = shortProductname;
  }

  public ProductResource startdate(Date startdate) {
    this.startdate = startdate;
    return this;
  }

  /**
   * Get startdate
   * @return startdate
   **/
  @JsonProperty("startdate")
  @ApiModelProperty(value = "")
  public Date getStartdate() {
    return startdate;
  }

  public void setStartdate(Date startdate) {
    this.startdate = startdate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductResource productResource = (ProductResource) o;
    return Objects.equals(this.backdatedinception, productResource.backdatedinception) &&
        Objects.equals(this.backdatedinceptionrange, productResource.backdatedinceptionrange) &&
        Objects.equals(this.effectivedate, productResource.effectivedate) &&
        Objects.equals(this.enddate, productResource.enddate) &&
        Objects.equals(this.links, productResource.links) &&
        Objects.equals(this.lobid, productResource.lobid) &&
        Objects.equals(this.productid, productResource.productid) &&
        Objects.equals(this.productname, productResource.productname) &&
        Objects.equals(this.riskstartdaterange, productResource.riskstartdaterange) &&
        Objects.equals(this.shortProductname, productResource.shortProductname) &&
        Objects.equals(this.startdate, productResource.startdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backdatedinception, backdatedinceptionrange, effectivedate, enddate, links, lobid, productid, productname, riskstartdaterange, shortProductname, startdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductResource {\n");
    
    sb.append("    backdatedinception: ").append(toIndentedString(backdatedinception)).append("\n");
    sb.append("    backdatedinceptionrange: ").append(toIndentedString(backdatedinceptionrange)).append("\n");
    sb.append("    effectivedate: ").append(toIndentedString(effectivedate)).append("\n");
    sb.append("    enddate: ").append(toIndentedString(enddate)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    lobid: ").append(toIndentedString(lobid)).append("\n");
    sb.append("    productid: ").append(toIndentedString(productid)).append("\n");
    sb.append("    productname: ").append(toIndentedString(productname)).append("\n");
    sb.append("    riskstartdaterange: ").append(toIndentedString(riskstartdaterange)).append("\n");
    sb.append("    shortProductname: ").append(toIndentedString(shortProductname)).append("\n");
    sb.append("    startdate: ").append(toIndentedString(startdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

