/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import demo.cosmos.core.policy.model.Link;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.validation.constraints.*;

/**
 * ProposalBeneficiaryInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class ProposalBeneficiaryInfo   {
  @JsonProperty("dob")
  private Date dob = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("links")
  private List<Link> links = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("nomineeName")
  private String nomineeName = null;

  @JsonProperty("nomineeRelation")
  private Integer nomineeRelation = null;

  @JsonProperty("nomineeType")
  private Integer nomineeType = null;

  @JsonProperty("proposerRelation")
  private Integer proposerRelation = null;

  public ProposalBeneficiaryInfo dob(Date dob) {
    this.dob = dob;
    return this;
  }

  /**
   * Get dob
   * @return dob
   **/
  @JsonProperty("dob")
  @ApiModelProperty(value = "")
  public Date getDob() {
    return dob;
  }

  public void setDob(Date dob) {
    this.dob = dob;
  }

  public ProposalBeneficiaryInfo gender(String gender) {
    this.gender = gender;
    return this;
  }

  /**
   * Get gender
   * @return gender
   **/
  @JsonProperty("gender")
  @ApiModelProperty(value = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public ProposalBeneficiaryInfo links(List<Link> links) {
    this.links = links;
    return this;
  }

  public ProposalBeneficiaryInfo addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
   **/
  @JsonProperty("links")
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public ProposalBeneficiaryInfo name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProposalBeneficiaryInfo nomineeName(String nomineeName) {
    this.nomineeName = nomineeName;
    return this;
  }

  /**
   * Get nomineeName
   * @return nomineeName
   **/
  @JsonProperty("nomineeName")
  @ApiModelProperty(value = "")
  public String getNomineeName() {
    return nomineeName;
  }

  public void setNomineeName(String nomineeName) {
    this.nomineeName = nomineeName;
  }

  public ProposalBeneficiaryInfo nomineeRelation(Integer nomineeRelation) {
    this.nomineeRelation = nomineeRelation;
    return this;
  }

  /**
   * Get nomineeRelation
   * @return nomineeRelation
   **/
  @JsonProperty("nomineeRelation")
  @ApiModelProperty(value = "")
  public Integer getNomineeRelation() {
    return nomineeRelation;
  }

  public void setNomineeRelation(Integer nomineeRelation) {
    this.nomineeRelation = nomineeRelation;
  }

  public ProposalBeneficiaryInfo nomineeType(Integer nomineeType) {
    this.nomineeType = nomineeType;
    return this;
  }

  /**
   * Get nomineeType
   * @return nomineeType
   **/
  @JsonProperty("nomineeType")
  @ApiModelProperty(value = "")
  public Integer getNomineeType() {
    return nomineeType;
  }

  public void setNomineeType(Integer nomineeType) {
    this.nomineeType = nomineeType;
  }

  public ProposalBeneficiaryInfo proposerRelation(Integer proposerRelation) {
    this.proposerRelation = proposerRelation;
    return this;
  }

  /**
   * Get proposerRelation
   * @return proposerRelation
   **/
  @JsonProperty("proposerRelation")
  @ApiModelProperty(value = "")
  public Integer getProposerRelation() {
    return proposerRelation;
  }

  public void setProposerRelation(Integer proposerRelation) {
    this.proposerRelation = proposerRelation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProposalBeneficiaryInfo proposalBeneficiaryInfo = (ProposalBeneficiaryInfo) o;
    return Objects.equals(this.dob, proposalBeneficiaryInfo.dob) &&
        Objects.equals(this.gender, proposalBeneficiaryInfo.gender) &&
        Objects.equals(this.links, proposalBeneficiaryInfo.links) &&
        Objects.equals(this.name, proposalBeneficiaryInfo.name) &&
        Objects.equals(this.nomineeName, proposalBeneficiaryInfo.nomineeName) &&
        Objects.equals(this.nomineeRelation, proposalBeneficiaryInfo.nomineeRelation) &&
        Objects.equals(this.nomineeType, proposalBeneficiaryInfo.nomineeType) &&
        Objects.equals(this.proposerRelation, proposalBeneficiaryInfo.proposerRelation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dob, gender, links, name, nomineeName, nomineeRelation, nomineeType, proposerRelation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProposalBeneficiaryInfo {\n");
    
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nomineeName: ").append(toIndentedString(nomineeName)).append("\n");
    sb.append("    nomineeRelation: ").append(toIndentedString(nomineeRelation)).append("\n");
    sb.append("    nomineeType: ").append(toIndentedString(nomineeType)).append("\n");
    sb.append("    proposerRelation: ").append(toIndentedString(proposerRelation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

