/*
 * Documentation for Policy service
 * API to handle policy related information
 *
 * OpenAPI spec version: 1.0
 * Contact: conatact@liberty.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package demo.cosmos.core.policy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * ProposalQuestionInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-11-14T18:57:01.638+05:30")
public class ProposalQuestionInfo   {
  @JsonProperty("questionAns")
  private Boolean questionAns = null;

  @JsonProperty("questionId")
  private Integer questionId = null;

  public ProposalQuestionInfo questionAns(Boolean questionAns) {
    this.questionAns = questionAns;
    return this;
  }

  /**
   * Get questionAns
   * @return questionAns
   **/
  @JsonProperty("questionAns")
  @ApiModelProperty(value = "")
  public Boolean isQuestionAns() {
    return questionAns;
  }

  public void setQuestionAns(Boolean questionAns) {
    this.questionAns = questionAns;
  }

  public ProposalQuestionInfo questionId(Integer questionId) {
    this.questionId = questionId;
    return this;
  }

  /**
   * Get questionId
   * @return questionId
   **/
  @JsonProperty("questionId")
  @ApiModelProperty(value = "")
  public Integer getQuestionId() {
    return questionId;
  }

  public void setQuestionId(Integer questionId) {
    this.questionId = questionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProposalQuestionInfo proposalQuestionInfo = (ProposalQuestionInfo) o;
    return Objects.equals(this.questionAns, proposalQuestionInfo.questionAns) &&
        Objects.equals(this.questionId, proposalQuestionInfo.questionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(questionAns, questionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProposalQuestionInfo {\n");
    
    sb.append("    questionAns: ").append(toIndentedString(questionAns)).append("\n");
    sb.append("    questionId: ").append(toIndentedString(questionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

