package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Agerange generated by hbm2java
 */
@Entity
@Table(name="agerange"
    ,catalog="test"
)
public class Agerange  implements java.io.Serializable {


     private Integer agerangeid;
     private String ageRange;
     private Set<Planbreakup> planbreakups = new HashSet<Planbreakup>(0);

    public Agerange() {
    }

	
    public Agerange(String ageRange) {
        this.ageRange = ageRange;
    }
    public Agerange(String ageRange, Set<Planbreakup> planbreakups) {
       this.ageRange = ageRange;
       this.planbreakups = planbreakups;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Agerangeid", unique=true, nullable=false)
    public Integer getAgerangeid() {
        return this.agerangeid;
    }
    
    public void setAgerangeid(Integer agerangeid) {
        this.agerangeid = agerangeid;
    }

    
    @Column(name="AgeRange", nullable=false, length=50)
    public String getAgeRange() {
        return this.ageRange;
    }
    
    public void setAgeRange(String ageRange) {
        this.ageRange = ageRange;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agerange")
    public Set<Planbreakup> getPlanbreakups() {
        return this.planbreakups;
    }
    
    public void setPlanbreakups(Set<Planbreakup> planbreakups) {
        this.planbreakups = planbreakups;
    }




}


