package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BeneficiaryInfoId generated by hbm2java
 */
@Embeddable
public class BeneficiaryInfoId implements java.io.Serializable {

	private Integer policyid;
	private String name;
	private Date dob;
	private String gender;
	private Integer relationProposer;
	private String nomineename;
	private Integer relationNominee;
	private Integer nomineeType;

	public BeneficiaryInfoId() {
	}

	public BeneficiaryInfoId(Integer policyid, String name, Date dob, String gender, Integer relationProposer,
			String nomineename, Integer relationNominee, Integer nomineeType) {
		this.policyid = policyid;
		this.name = name;
		this.dob = dob;
		this.gender = gender;
		this.relationProposer = relationProposer;
		this.nomineename = nomineename;
		this.relationNominee = relationNominee;
		this.nomineeType = nomineeType;
	}

	@Column(name = "Policyid")
	public Integer getPolicyid() {
		return this.policyid;
	}

	public void setPolicyid(Integer policyid) {
		this.policyid = policyid;
	}

	@Column(name = "Name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Gender", length = 2)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "Relation_proposer")
	public Integer getRelationProposer() {
		return this.relationProposer;
	}

	public void setRelationProposer(Integer relationProposer) {
		this.relationProposer = relationProposer;
	}

	@Column(name = "nomineename", length = 100)
	public String getNomineename() {
		return this.nomineename;
	}

	public void setNomineename(String nomineename) {
		this.nomineename = nomineename;
	}

	@Column(name = "Relation_nominee")
	public Integer getRelationNominee() {
		return this.relationNominee;
	}

	public void setRelationNominee(Integer relationNominee) {
		this.relationNominee = relationNominee;
	}

	@Column(name = "Nominee_type")
	public Integer getNomineeType() {
		return this.nomineeType;
	}

	public void setNomineeType(Integer nomineeType) {
		this.nomineeType = nomineeType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BeneficiaryInfoId))
			return false;
		BeneficiaryInfoId castOther = (BeneficiaryInfoId) other;

		return ((this.getPolicyid() == castOther.getPolicyid()) || (this.getPolicyid() != null
				&& castOther.getPolicyid() != null && this.getPolicyid().equals(castOther.getPolicyid())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getDob() == castOther.getDob()) || (this.getDob() != null && castOther.getDob() != null
						&& this.getDob().equals(castOther.getDob())))
				&& ((this.getGender() == castOther.getGender()) || (this.getGender() != null
						&& castOther.getGender() != null && this.getGender().equals(castOther.getGender())))
				&& ((this.getRelationProposer() == castOther.getRelationProposer())
						|| (this.getRelationProposer() != null && castOther.getRelationProposer() != null
								&& this.getRelationProposer().equals(castOther.getRelationProposer())))
				&& ((this.getNomineename() == castOther.getNomineename())
						|| (this.getNomineename() != null && castOther.getNomineename() != null
								&& this.getNomineename().equals(castOther.getNomineename())))
				&& ((this.getRelationNominee() == castOther.getRelationNominee())
						|| (this.getRelationNominee() != null && castOther.getRelationNominee() != null
								&& this.getRelationNominee().equals(castOther.getRelationNominee())))
				&& ((this.getNomineeType() == castOther.getNomineeType())
						|| (this.getNomineeType() != null && castOther.getNomineeType() != null
								&& this.getNomineeType().equals(castOther.getNomineeType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPolicyid() == null ? 0 : this.getPolicyid().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDob() == null ? 0 : this.getDob().hashCode());
		result = 37 * result + (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37 * result + (getRelationProposer() == null ? 0 : this.getRelationProposer().hashCode());
		result = 37 * result + (getNomineename() == null ? 0 : this.getNomineename().hashCode());
		result = 37 * result + (getRelationNominee() == null ? 0 : this.getRelationNominee().hashCode());
		result = 37 * result + (getNomineeType() == null ? 0 : this.getNomineeType().hashCode());
		return result;
	}

}
