package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Choices generated by hbm2java
 */
@Entity
@Table(name="choices"
    ,catalog="test"
)
public class Choices  implements java.io.Serializable {


     private Integer choiceid;
     private String choicevalue;
     private Set<ProductquestionChoice> productquestionChoices = new HashSet<ProductquestionChoice>(0);

    public Choices() {
    }

    public Choices(String choicevalue, Set<ProductquestionChoice> productquestionChoices) {
       this.choicevalue = choicevalue;
       this.productquestionChoices = productquestionChoices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Choiceid", unique=true, nullable=false)
    public Integer getChoiceid() {
        return this.choiceid;
    }
    
    public void setChoiceid(Integer choiceid) {
        this.choiceid = choiceid;
    }

    
    @Column(name="choicevalue", length=30)
    public String getChoicevalue() {
        return this.choicevalue;
    }
    
    public void setChoicevalue(String choicevalue) {
        this.choicevalue = choicevalue;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="choices")
    public Set<ProductquestionChoice> getProductquestionChoices() {
        return this.productquestionChoices;
    }
    
    public void setProductquestionChoices(Set<ProductquestionChoice> productquestionChoices) {
        this.productquestionChoices = productquestionChoices;
    }




}


