package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="customers"
    ,catalog="test"
)
public class Customers  implements java.io.Serializable {


     private Integer customerid;
     private String name;
     private Set<Policydetails> policydetailses = new HashSet<Policydetails>(0);
     private Set<Customeraddress> customeraddresses = new HashSet<Customeraddress>(0);

    public Customers() {
    }

    public Customers(String name, Set<Policydetails> policydetailses, Set<Customeraddress> customeraddresses) {
       this.name = name;
       this.policydetailses = policydetailses;
       this.customeraddresses = customeraddresses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Customerid", unique=true, nullable=false)
    public Integer getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    
    @Column(name="Name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customers")
    public Set<Policydetails> getPolicydetailses() {
        return this.policydetailses;
    }
    
    public void setPolicydetailses(Set<Policydetails> policydetailses) {
        this.policydetailses = policydetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customers")
    public Set<Customeraddress> getCustomeraddresses() {
        return this.customeraddresses;
    }
    
    public void setCustomeraddresses(Set<Customeraddress> customeraddresses) {
        this.customeraddresses = customeraddresses;
    }

}


