package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Customeraddress generated by hbm2java
 */
@Entity
@Table(name="customeraddress"
    ,catalog="test"
)
public class Customeraddress  implements java.io.Serializable {


     private int policyid;
     private Customers customers;
     private String address1;
     private String address2;
     private String address3;
     private String state;
     private String district;
     private String city;
     private String pincode;
     private String emailId;
     private String mobile;
     private String telephone;

    public Customeraddress() {
    }

	
    public Customeraddress(int policyid) {
        this.policyid = policyid;
    }
    public Customeraddress(int policyid, Customers customers, String address1, String address2, String address3, String state, String district, String city, String pincode, String emailId, String mobile, String telephone) {
       this.policyid = policyid;
       this.customers = customers;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.state = state;
       this.district = district;
       this.city = city;
       this.pincode = pincode;
       this.emailId = emailId;
       this.mobile = mobile;
       this.telephone = telephone;
    }
   
     @Id 

    
    @Column(name="Policyid", unique=true, nullable=false)
    public int getPolicyid() {
        return this.policyid;
    }
    
    public void setPolicyid(int policyid) {
        this.policyid = policyid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customerid")
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    
    @Column(name="Address1", length=100)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="Address2", length=100)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="Address3", length=100)
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    
    @Column(name="State", length=50)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="District", length=50)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="City", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="Pincode", length=50)
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    
    @Column(name="EmailID", length=50)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="Mobile", length=50)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="Telephone", length=50)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }




}


