package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlanbreakupId generated by hbm2java
 */
@Embeddable
public class PlanbreakupId  implements java.io.Serializable {


     private int planid;
     private long si;
     private int agerange;
     private long premium;
     private Long cgst;
     private Long sgst;
     private Long igst;
     private long gp;

    public PlanbreakupId() {
    }

	
    public PlanbreakupId(int planid, long si, int agerange, long premium, long gp) {
        this.planid = planid;
        this.si = si;
        this.agerange = agerange;
        this.premium = premium;
        this.gp = gp;
    }
    public PlanbreakupId(int planid, long si, int agerange, long premium, Long cgst, Long sgst, Long igst, long gp) {
       this.planid = planid;
       this.si = si;
       this.agerange = agerange;
       this.premium = premium;
       this.cgst = cgst;
       this.sgst = sgst;
       this.igst = igst;
       this.gp = gp;
    }
   


    @Column(name="Planid", nullable=false)
    public int getPlanid() {
        return this.planid;
    }
    
    public void setPlanid(int planid) {
        this.planid = planid;
    }


    @Column(name="SI", nullable=false, precision=10, scale=0)
    public long getSi() {
        return this.si;
    }
    
    public void setSi(long si) {
        this.si = si;
    }


    @Column(name="Agerange", nullable=false)
    public int getAgerange() {
        return this.agerange;
    }
    
    public void setAgerange(int agerange) {
        this.agerange = agerange;
    }


    @Column(name="Premium", nullable=false, precision=10, scale=0)
    public long getPremium() {
        return this.premium;
    }
    
    public void setPremium(long premium) {
        this.premium = premium;
    }


    @Column(name="CGST", precision=10, scale=0)
    public Long getCgst() {
        return this.cgst;
    }
    
    public void setCgst(Long cgst) {
        this.cgst = cgst;
    }


    @Column(name="SGST", precision=10, scale=0)
    public Long getSgst() {
        return this.sgst;
    }
    
    public void setSgst(Long sgst) {
        this.sgst = sgst;
    }


    @Column(name="IGST", precision=10, scale=0)
    public Long getIgst() {
        return this.igst;
    }
    
    public void setIgst(Long igst) {
        this.igst = igst;
    }


    @Column(name="GP", nullable=false, precision=10, scale=0)
    public long getGp() {
        return this.gp;
    }
    
    public void setGp(long gp) {
        this.gp = gp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PlanbreakupId) ) return false;
		 PlanbreakupId castOther = ( PlanbreakupId ) other; 
         
		 return (this.getPlanid()==castOther.getPlanid())
 && (this.getSi()==castOther.getSi())
 && (this.getAgerange()==castOther.getAgerange())
 && (this.getPremium()==castOther.getPremium())
 && ( (this.getCgst()==castOther.getCgst()) || ( this.getCgst()!=null && castOther.getCgst()!=null && this.getCgst().equals(castOther.getCgst()) ) )
 && ( (this.getSgst()==castOther.getSgst()) || ( this.getSgst()!=null && castOther.getSgst()!=null && this.getSgst().equals(castOther.getSgst()) ) )
 && ( (this.getIgst()==castOther.getIgst()) || ( this.getIgst()!=null && castOther.getIgst()!=null && this.getIgst().equals(castOther.getIgst()) ) )
 && (this.getGp()==castOther.getGp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPlanid();
         result = 37 * result + (int) this.getSi();
         result = 37 * result + this.getAgerange();
         result = 37 * result + (int) this.getPremium();
         result = 37 * result + ( getCgst() == null ? 0 : this.getCgst().hashCode() );
         result = 37 * result + ( getSgst() == null ? 0 : this.getSgst().hashCode() );
         result = 37 * result + ( getIgst() == null ? 0 : this.getIgst().hashCode() );
         result = 37 * result + (int) this.getGp();
         return result;
   }   


}


