package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plantype generated by hbm2java
 */
@Entity
@Table(name="plantype"
    ,catalog="test"
)
public class Plantype  implements java.io.Serializable {


     private Integer planid;
     private Product product;
     private String policytype;
     private Set<Planbreakup> planbreakups = new HashSet<Planbreakup>(0);

    public Plantype() {
    }

	
    public Plantype(Product product, String policytype) {
        this.product = product;
        this.policytype = policytype;
    }
    public Plantype(Product product, String policytype, Set<Planbreakup> planbreakups) {
       this.product = product;
       this.policytype = policytype;
       this.planbreakups = planbreakups;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Planid", unique=true, nullable=false)
    public Integer getPlanid() {
        return this.planid;
    }
    
    public void setPlanid(Integer planid) {
        this.planid = planid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Productid", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="policytype", nullable=false, length=50)
    public String getPolicytype() {
        return this.policytype;
    }
    
    public void setPolicytype(String policytype) {
        this.policytype = policytype;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="plantype")
    public Set<Planbreakup> getPlanbreakups() {
        return this.planbreakups;
    }
    
    public void setPlanbreakups(Set<Planbreakup> planbreakups) {
        this.planbreakups = planbreakups;
    }




}


