package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Policydetails generated by hbm2java
 */
@Entity
@Table(name="policydetails"
    ,catalog="test"
)
public class Policydetails  implements java.io.Serializable {


     private Integer policyid;
     private Customers customers;
     private Policystatus policystatus;
     private Product product;
     private int planId;
     private Date policyStartDate;
     private Date policyEndDate;
     private int affinityid;
     private int branchId;
     private String certificateno;
     private Date lastUpdatedDate;
     private int lastUpdatedBy;
     private String employeecode;
     private int policyterm;
     private Integer masterpolicyno;
     private Integer covernoteno;
     private Set<BeneficiaryInfo> beneficiaryInfos = new HashSet<BeneficiaryInfo>(0);
     private Set<Productanswers> productanswerses = new HashSet<Productanswers>(0);

    public Policydetails() {
    }

	
    public Policydetails(Policystatus policystatus, Product product, int planId, Date policyStartDate, Date policyEndDate, int affinityid, int branchId, Date lastUpdatedDate, int lastUpdatedBy, int policyterm) {
        this.policystatus = policystatus;
        this.product = product;
        this.planId = planId;
        this.policyStartDate = policyStartDate;
        this.policyEndDate = policyEndDate;
        this.affinityid = affinityid;
        this.branchId = branchId;
        this.lastUpdatedDate = lastUpdatedDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.policyterm = policyterm;
    }
    public Policydetails(Customers customers, Policystatus policystatus, Product product, int planId, Date policyStartDate, Date policyEndDate, int affinityid, int branchId, String certificateno, Date lastUpdatedDate, int lastUpdatedBy, String employeecode, int policyterm, Integer masterpolicyno, Integer covernoteno, Set<BeneficiaryInfo> beneficiaryInfos, Set<Productanswers> productanswerses) {
       this.customers = customers;
       this.policystatus = policystatus;
       this.product = product;
       this.planId = planId;
       this.policyStartDate = policyStartDate;
       this.policyEndDate = policyEndDate;
       this.affinityid = affinityid;
       this.branchId = branchId;
       this.certificateno = certificateno;
       this.lastUpdatedDate = lastUpdatedDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.employeecode = employeecode;
       this.policyterm = policyterm;
       this.masterpolicyno = masterpolicyno;
       this.covernoteno = covernoteno;
       this.beneficiaryInfos = beneficiaryInfos;
       this.productanswerses = productanswerses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Policyid", unique=true, nullable=false)
    public Integer getPolicyid() {
        return this.policyid;
    }
    
    public void setPolicyid(Integer policyid) {
        this.policyid = policyid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Customerid")
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PolicyStatusID", nullable=false)
    public Policystatus getPolicystatus() {
        return this.policystatus;
    }
    
    public void setPolicystatus(Policystatus policystatus) {
        this.policystatus = policystatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ProductID", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="PlanID", nullable=false)
    public int getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(int planId) {
        this.planId = planId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PolicyStartDate", nullable=false, length=10)
    public Date getPolicyStartDate() {
        return this.policyStartDate;
    }
    
    public void setPolicyStartDate(Date policyStartDate) {
        this.policyStartDate = policyStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PolicyEndDate", nullable=false, length=10)
    public Date getPolicyEndDate() {
        return this.policyEndDate;
    }
    
    public void setPolicyEndDate(Date policyEndDate) {
        this.policyEndDate = policyEndDate;
    }

    
    @Column(name="Affinityid", nullable=false)
    public int getAffinityid() {
        return this.affinityid;
    }
    
    public void setAffinityid(int affinityid) {
        this.affinityid = affinityid;
    }

    
    @Column(name="BranchId", nullable=false)
    public int getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }

    
    @Column(name="Certificateno", length=50)
    public String getCertificateno() {
        return this.certificateno;
    }
    
    public void setCertificateno(String certificateno) {
        this.certificateno = certificateno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LastUpdatedDate", nullable=false, length=10)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="LastUpdatedBy", nullable=false)
    public int getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(int lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    
    @Column(name="Employeecode", length=50)
    public String getEmployeecode() {
        return this.employeecode;
    }
    
    public void setEmployeecode(String employeecode) {
        this.employeecode = employeecode;
    }

    
    @Column(name="Policyterm", nullable=false)
    public int getPolicyterm() {
        return this.policyterm;
    }
    
    public void setPolicyterm(int policyterm) {
        this.policyterm = policyterm;
    }

    
    @Column(name="Masterpolicyno")
    public Integer getMasterpolicyno() {
        return this.masterpolicyno;
    }
    
    public void setMasterpolicyno(Integer masterpolicyno) {
        this.masterpolicyno = masterpolicyno;
    }

    
    @Column(name="Covernoteno")
    public Integer getCovernoteno() {
        return this.covernoteno;
    }
    
    public void setCovernoteno(Integer covernoteno) {
        this.covernoteno = covernoteno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="policydetails")
    public Set<BeneficiaryInfo> getBeneficiaryInfos() {
        return this.beneficiaryInfos;
    }
    
    public void setBeneficiaryInfos(Set<BeneficiaryInfo> beneficiaryInfos) {
        this.beneficiaryInfos = beneficiaryInfos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="policydetails")
    public Set<Productanswers> getProductanswerses() {
        return this.productanswerses;
    }
    
    public void setProductanswerses(Set<Productanswers> productanswerses) {
        this.productanswerses = productanswerses;
    }




}


