package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Policystatus generated by hbm2java
 */
@Entity
@Table(name="policystatus"
    ,catalog="test"
)
public class Policystatus  implements java.io.Serializable {


     private Integer policystatusid;
     private String status;
     private Set<Policydetails> policydetailses = new HashSet<Policydetails>(0);

    public Policystatus() {
    }

    public Policystatus(String status, Set<Policydetails> policydetailses) {
       this.status = status;
       this.policydetailses = policydetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Policystatusid", unique=true, nullable=false)
    public Integer getPolicystatusid() {
        return this.policystatusid;
    }
    
    public void setPolicystatusid(Integer policystatusid) {
        this.policystatusid = policystatusid;
    }

    
    @Column(name="status", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="policystatus")
    public Set<Policydetails> getPolicydetailses() {
        return this.policydetailses;
    }
    
    public void setPolicydetailses(Set<Policydetails> policydetailses) {
        this.policydetailses = policydetailses;
    }




}


