package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductanswersId generated by hbm2java
 */
@Embeddable
public class ProductanswersId  implements java.io.Serializable {


     private Integer policyid;
     private Integer questionid;
     private Boolean ans;

    public ProductanswersId() {
    }

    public ProductanswersId(Integer policyid, Integer questionid, Boolean ans) {
       this.policyid = policyid;
       this.questionid = questionid;
       this.ans = ans;
    }
   


    @Column(name="Policyid")
    public Integer getPolicyid() {
        return this.policyid;
    }
    
    public void setPolicyid(Integer policyid) {
        this.policyid = policyid;
    }


    @Column(name="Questionid")
    public Integer getQuestionid() {
        return this.questionid;
    }
    
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }


    @Column(name="Ans")
    public Boolean getAns() {
        return this.ans;
    }
    
    public void setAns(Boolean ans) {
        this.ans = ans;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductanswersId) ) return false;
		 ProductanswersId castOther = ( ProductanswersId ) other; 
         
		 return ( (this.getPolicyid()==castOther.getPolicyid()) || ( this.getPolicyid()!=null && castOther.getPolicyid()!=null && this.getPolicyid().equals(castOther.getPolicyid()) ) )
 && ( (this.getQuestionid()==castOther.getQuestionid()) || ( this.getQuestionid()!=null && castOther.getQuestionid()!=null && this.getQuestionid().equals(castOther.getQuestionid()) ) )
 && ( (this.getAns()==castOther.getAns()) || ( this.getAns()!=null && castOther.getAns()!=null && this.getAns().equals(castOther.getAns()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPolicyid() == null ? 0 : this.getPolicyid().hashCode() );
         result = 37 * result + ( getQuestionid() == null ? 0 : this.getQuestionid().hashCode() );
         result = 37 * result + ( getAns() == null ? 0 : this.getAns().hashCode() );
         return result;
   }   


}


