package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="test"
)
public class Product  implements java.io.Serializable {


     private Integer productid;
     private String productname;
     private Integer lobid;
     private String shortProductname;
     private Date startdate;
     private Date enddate;
     private Date lastupdateddate;
     private Date effectivedate;
     private Integer riskstartdaterange;
     private Boolean backdatedinception;
     private Integer backdatedinceptionrange;
     private String policynumberingformat;
     private Set<Plantype> plantypes = new HashSet<Plantype>(0);
     private Set<Productquestions> productquestionses = new HashSet<Productquestions>(0);
     private Set<Policydetails> policydetailses = new HashSet<Policydetails>(0);

    public Product() {
    }

    public Product(String productname, Integer lobid, String shortProductname, Date startdate, Date enddate, Date lastupdateddate, Date effectivedate, Integer riskstartdaterange, Boolean backdatedinception, Integer backdatedinceptionrange, String policynumberingformat, Set<Plantype> plantypes, Set<Productquestions> productquestionses, Set<Policydetails> policydetailses) {
       this.productname = productname;
       this.lobid = lobid;
       this.shortProductname = shortProductname;
       this.startdate = startdate;
       this.enddate = enddate;
       this.lastupdateddate = lastupdateddate;
       this.effectivedate = effectivedate;
       this.riskstartdaterange = riskstartdaterange;
       this.backdatedinception = backdatedinception;
       this.backdatedinceptionrange = backdatedinceptionrange;
       this.policynumberingformat = policynumberingformat;
       this.plantypes = plantypes;
       this.productquestionses = productquestionses;
       this.policydetailses = policydetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Productid", unique=true, nullable=false)
    public Integer getProductid() {
        return this.productid;
    }
    
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    
    @Column(name="Productname", length=150)
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }

    
    @Column(name="Lobid")
    public Integer getLobid() {
        return this.lobid;
    }
    
    public void setLobid(Integer lobid) {
        this.lobid = lobid;
    }

    
    @Column(name="ShortProductname", length=20)
    public String getShortProductname() {
        return this.shortProductname;
    }
    
    public void setShortProductname(String shortProductname) {
        this.shortProductname = shortProductname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Startdate", length=10)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Enddate", length=10)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Lastupdateddate", length=10)
    public Date getLastupdateddate() {
        return this.lastupdateddate;
    }
    
    public void setLastupdateddate(Date lastupdateddate) {
        this.lastupdateddate = lastupdateddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Effectivedate", length=10)
    public Date getEffectivedate() {
        return this.effectivedate;
    }
    
    public void setEffectivedate(Date effectivedate) {
        this.effectivedate = effectivedate;
    }

    
    @Column(name="Riskstartdaterange")
    public Integer getRiskstartdaterange() {
        return this.riskstartdaterange;
    }
    
    public void setRiskstartdaterange(Integer riskstartdaterange) {
        this.riskstartdaterange = riskstartdaterange;
    }

    
    @Column(name="Backdatedinception")
    public Boolean getBackdatedinception() {
        return this.backdatedinception;
    }
    
    public void setBackdatedinception(Boolean backdatedinception) {
        this.backdatedinception = backdatedinception;
    }

    
    @Column(name="Backdatedinceptionrange")
    public Integer getBackdatedinceptionrange() {
        return this.backdatedinceptionrange;
    }
    
    public void setBackdatedinceptionrange(Integer backdatedinceptionrange) {
        this.backdatedinceptionrange = backdatedinceptionrange;
    }

    
    @Column(name="Policynumberingformat", length=30)
    public String getPolicynumberingformat() {
        return this.policynumberingformat;
    }
    
    public void setPolicynumberingformat(String policynumberingformat) {
        this.policynumberingformat = policynumberingformat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Plantype> getPlantypes() {
        return this.plantypes;
    }
    
    public void setPlantypes(Set<Plantype> plantypes) {
        this.plantypes = plantypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Productquestions> getProductquestionses() {
        return this.productquestionses;
    }
    
    public void setProductquestionses(Set<Productquestions> productquestionses) {
        this.productquestionses = productquestionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<Policydetails> getPolicydetailses() {
        return this.policydetailses;
    }
    
    public void setPolicydetailses(Set<Policydetails> policydetailses) {
        this.policydetailses = policydetailses;
    }




}


