package demo.cosmos.core.policy.dao.entity;
// Generated Nov 14, 2018 7:02:50 PM by Hibernate Tools 5.2.10.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductquestionChoice generated by hbm2java
 */
@Entity
@Table(name="productquestion_choice"
    ,catalog="test"
)
public class ProductquestionChoice  implements java.io.Serializable {


     private ProductquestionChoiceId id;
     private Choices choices;
     private Productquestions productquestions;

    public ProductquestionChoice() {
    }

	
    public ProductquestionChoice(ProductquestionChoiceId id) {
        this.id = id;
    }
    public ProductquestionChoice(ProductquestionChoiceId id, Choices choices, Productquestions productquestions) {
       this.id = id;
       this.choices = choices;
       this.productquestions = productquestions;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="questionid", column=@Column(name="Questionid") ), 
        @AttributeOverride(name="choiceid", column=@Column(name="Choiceid") ) } )
    public ProductquestionChoiceId getId() {
        return this.id;
    }
    
    public void setId(ProductquestionChoiceId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Choiceid", insertable=false, updatable=false)
    public Choices getChoices() {
        return this.choices;
    }
    
    public void setChoices(Choices choices) {
        this.choices = choices;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Questionid", insertable=false, updatable=false)
    public Productquestions getProductquestions() {
        return this.productquestions;
    }
    
    public void setProductquestions(Productquestions productquestions) {
        this.productquestions = productquestions;
    }




}


